@startuml
!include <azure/AzureCommon>
!include <azure/Web/AzureWebApp>
!include <azure/Databases/AzureSqlDatabase>
!include <azure/Storage/AzureQueueStorage>
!include <C4/C4_Container>

AddElementTag("queue", $bgColor="white", $fontColor=$PERSON_BG_COLOR)
AddRelTag("message", $lineStyle=DashedLine())
Person(tu, "Trust User", "")
System_Boundary(cwt, "CWT System") {
  Container(web, "CWT Web App", "C#, ASP.NET Core 2.1 MVC", $descr="Front end for the CWT system", $sprite="AzureWebApp")
  Container(col, "Collection Service", "C#, .NET", $descr="Process file imports", $sprite="AzureWebApp")
  Container(mm, "Merge and Match Service", "C#, .NET", $descr="Match existing records, create new records", $sprite="AzureWebApp")
  Container(der, "Derivation Service", "C#, .NET", $descr="Calculate derived fields", $sprite="AzureWebApp")
  Container(cmp, "Compliance Service", "C#, .NET", $descr="Rules engine applying compliance rules", $sprite="AzureWebApp")
  Container(syc, "Reports Synchroniser Service", "C#, .NET", $descr="Synchronise reporting data", $sprite="AzureWebApp")
  ContainerDb(db, "CWT Database", "MS SQL Server", $sprite="AzureSqlDatabase")
  ContainerQueue(qu, "Queue", "SSQS", "FIFO Queue for intra-service messaging", $sprite="AzureQueueStorage", $tags="queue")
}

System_Boundary(id, "Identity") {
  Container_Ext(sso, "SSO", "OAuth", $descr="Authentication", $sprite="AzureWebApp")
}

System_Boundary(scds, "SCDS") {
  Container_Ext(auth, "ACL", "", $descr="Role based authorisation", $sprite="AzureWebApp")
  Container_Ext(imp, "Import", "", $descr="File import and simple validation", $sprite="AzureWebApp")
}

Rel_L(tu, sso, "Authenticates with", "https")
Rel_U(web, auth, "Authorises with", "https")
Rel(tu, web, "Signs in", "https")
Rel(tu, web, "Uploads CWT Data", "https")
Rel_D(web, col, "Imports CWT Data using", "")
Rel_U(col, imp, "Uses", "")
'Rel(col, mm, "Supplies imported data", "")
Rel(mm, db, "Queries from", "SQL")
'Rel(mm, der, "", "")
'Rel(der, cmp, "", "")
'Rel_U(cmp, syc, "", "")
Rel_U(syc, db, "Writes to", "SQL")

BiRel_U(qu, col, "Messaging", "", $tags="message")
BiRel_U(qu, mm, "Messaging", "", $tags="message")
BiRel_L(qu, der, "Messaging", "", $tags="message")
BiRel_D(qu, cmp, "Messaging", "", $tags="message")
BiRel_D(qu, syc, "Messaging", "", $tags="message")

Lay_L(imp, auth)

LAYOUT_WITH_LEGEND()

@enduml
