@startuml
|#LightGray|S1| Stage 1 - Collection
|#White|S2| Stage 2 - Match and Merge
|#LightGray|S3| Stage 3 - Derivation
|#White|S4| Stage 4 - Report Synchronizer
|S1|
:File Uploaded;
#Orange:Pre-Merge Validation|
if (Record passed simple validation?) then (no)
  :Reject record(s)] 
  end 
else (yes)
|S2|
endif  
#Orange:Post-Merge Validation|
if (Post Merge Validation passed) then (no)
  :Reject record(s)] 
  end 
else (yes)
  #Orange:Match and Merge Rules|
  split
   #Orange:Merge with existing\nrecord|
  split again
   #Orange:New record\ncreated|
  end split
endif
|S3|
#Orange:Derivation rules / calculation|
|S4|
split
  #Orange:Patient search|
  detach
split again
  #Orange:Preview|
  detach  
split again
  #Orange:Download| 
  detach  
split again
  #Orange:Reporting functionality| 
  detach    
end split
@enduml
