@startuml cwt-data-flow

'!include <C4/C4_Container>
!$smallPerson = $person{scale=0.5}
'left to right direction
skinparam Shadowing false
skinparam Frame {
  BorderColor #Transparent
}

package "Data Flow" as df {
  component "Electronic Referral System" as ers  
  rectangle "National Screening Service" as nss
  rectangle "Rapid Diagnostic Centres" as rdc
  rectangle "Emergency Presentations" as ep


  component "Patient Administration System" as pas
  component "Diagnostic Systems" as ds
  component "Oncology Systems" as os

  usecase "Data Collection" as dc

  frame "<color:#Lavender><$smallPerson></color><color:#LightCyan><$smallPerson></color>" as f1 {
    usecase "Pre-validation" as pvd
    component lcs [
      <b><u>Local Cancer System  
      ====
      Somerset Cancer Register (SCR)
      Infoflex 
    ]
  }
  component "<b><u>Cancer Waiting Times System" as cwt

  frame "<color:#LightGrey><$smallPerson></color>" as f7 {
    rectangle "ex-PHE\n(now NHSD)" as nhsd 
  } 

  component ncras [
    Other Cancer
    Reporting Systems
    ----
    e.g. NCRAS
  ]

  frame "<color:#Plum><$smallPerson></color>" as f8 {
    component "Trusted Research Environment" as tre
  } 
  frame "<color:#Lavender><$smallPerson></color><color:#LightCyan><$smallPerson></color>" as f2 {
    component "Other Bespoke System" as oth
  }
  database db [
    CWT
    Database
  ]

  artifact rpt [
  Previews
  ----
  Reports
  ]
  
  usecase "1" as p1a #Cyan
  usecase "1" as p1b #Cyan
  usecase "1" as p1c #Cyan
  usecase "1" as p1d #Cyan   
  usecase "2-5" as p25a #Cyan
  usecase "2-5" as p25b #Cyan
  usecase "2-5" as p25c #Cyan  

  usecase "Provisional" as prov
  usecase "Final" as final

  usecase "Validation" as vld2 
  artifact "Extract" as ex
  usecase "Upload" as up
  
  usecase "Validation" as vld
  frame "<color:#GreenYellow><$smallPerson></color>" as f3 {
    rectangle "NHSE" as nhse
  }
  frame "<color:#MistyRose><$smallPerson></color>" as f4 {
    rectangle "CCGs/ICSs" as ics
  }
  frame "<color:#DarkOrange><$smallPerson></color>" as f5 {
    rectangle "Cancer Alliances" as ca
  }  
  frame "<color:#Lavender><$smallPerson></color><color:#Gold><$smallPerson></color>" as f6 {
    rectangle "Trusts" as ht
  }  


  component "CWT Dashboard" as cdb
  artifact "CWT National Reports/\nCompliance Reports" as frpt

  frame "<color:#Red><$smallPerson></color>" as f9 {
    component "Cancer Alliance Workspace" as wks
  }

}



ers .. p1a
p1a ...... dc

nss .. p1b
p1b ...... dc

rdc .. p1c
p1c ...... dc

ep .. p1d
p1d ...... dc

pas .. p25a
p25a .... dc
ds .. p25b

p25b .. dc

os .. p25c
p25c .. dc

dc --> lcs
dc --> oth

up --> cwt

lcs --> ex : Automated
ex -> up

cwt -> db

lcs -> pvd
pvd -> lcs

oth ..> ex : Manual
oth --> ex : Automated

lcs <.. vld
vld .. cwt

vld2 .. cwt
oth <.. vld2

db ...> nhsd
nhsd ..> ncras
db --> tre

cwt --> rpt

prov . rpt
final . prov

rpt --> nhse
rpt --> ics
rpt --> ca
rpt --> ht

nhse ..> cdb
nhse ..> frpt

frpt .> wks
ca <.. wks : reports to

' layout 
up -[#hidden] vld
vld2 -[#hidden] ex

' end-layout

@enduml