@startuml

left to right direction
!include https://raw.githubusercontent.com/nhsx/dt-public/main/CWT/Process/patient-pathway.puml
!include https://raw.githubusercontent.com/nhsx/dt-public/main/CWT/Process/data-flow.puml
!include https://raw.githubusercontent.com/nhsx/dt-public/main/CWT/Process/user-types.puml

@enduml