@startuml 
skinparam Shadowing false
'left to right direction


!include https://raw.githubusercontent.com/nhsx/dt-public/main/CWT/Process/user-types.puml
!include https://raw.githubusercontent.com/nhsx/dt-public/main/CWT/Process/data-flow.puml
!include https://raw.githubusercontent.com/nhsx/dt-public/main/CWT/Process/patient-pathway.puml

@enduml