@startuml
!include <C4/C4_Container>

left to right direction

HIDE_STEREOTYPE()
SHOW_PERSON_PORTRAIT()

!include use-case-ca-analyst-1.puml
!include use-case-ca-analyst-2.puml
!include use-case-ca-perf-manager.puml
!include use-case-ccg-analyst-1.puml
!include use-case-nhse-analyst-1.puml
!include use-case-nhse-analyst-2.puml

@enduml