@startuml use-case-nhse-analyst-1
package "P2, 25.01.22" {

database "CWT\nDatabase" as db
database "Arden & GEM" as agm
usecase "Download\nand transform" as md2
artifact "Combined Aggregated Reports" as cdf2
usecase "Create aggregate reports" as car
artifact "NHSE aggregate reports" as rpt2
usecase "Check\nreports match" as chk
artifact "CWT Aggregate Reports" as rpt1
actor "NHSE Analyst" as na #GreenYellow

db -> agm
agm -> car
car -> rpt2
rpt2 -> chk
chk <- cdf2
cdf2 <- md2
md2 <- rpt1

na --> md2 : manual\nto file shares
na --> car : R-scripts
na --> chk

}
@enduml