@startuml cwt-user-types
'left to right direction

!include <C4/C4_Container>

HIDE_STEREOTYPE()
SHOW_PERSON_PORTRAIT()

UpdateElementStyle(person, $fontColor="black")

skinparam Shadowing false

package "User Types" as ut {

package "Other Analysts" as oa {
  Person("nhse.analyst", "NHSE Analyst", "") #GreenYellow 
  Person("tre.analyst", "TRE Analyst", "") #Plum
  Person("nhsd.analyst", "NHSD Analyst (ex-PHE)", "") #LightGrey
}

package "Data Uploaders" as du {

  Person("cancer.pathway.analyst", "Cancer Pathway Analyst", "") #LightCyan
  Person("cancer.data.manager", "Cancer Data Manager", "") #Lavender

}

package "CA/ICS/CCG Data Analysts" as da {
  Person("ca.analyst", "CA Analyst", "") #DarkOrange
  Person("ics.analyst", "ICS/CCG Analyst", "") #MistyRose   

  ca.analyst -[#hidden] ics.analyst
  ics.analyst -[#hidden] tre.analyst
  tre.analyst -[#hidden] nhsd.analyst
}

package "Secondary Data Consumers" as dc1 {
  Person("cancer.perf.lead", "Cancer Performance Lead", "") #Gold   
  Person("cancer.alliance.fd.lead", "Cancer Alliance Delivery Lead", "") #Red
}

}

'du -[#hidden] da
'da -[#hidden] dc1
'dc1 -[#hidden] oa

@enduml