@startuml
'left to right direction

!include <C4/C4_Container>

HIDE_STEREOTYPE()
SHOW_PERSON_PORTRAIT()

skinparam Shadowing false


package "User Types" {

  Person("cancer.perf.lead", "Cancer Performance Lead", "") #Gold   
  Person("cancer.pathway.analyst", "Cancer Pathway Analyst", "") #LightCyan
  Person("cancer.data.manager", "Cancer Data Manager", "") #Lavender

  Person("nhse.analyst", "NHSE Analyst", "") #GreenYellow   
  Person("cancer.alliance.fd.lead", "Cancer Alliance FD/RDC Lead", "") #Red
  Person("ca.analyst", "CA Analyst", "") #DarkOrange

  Person("ics.analyst", "ICS/CCG Analyst", "") #MistyRose   
  Person("tre.analyst", "TRE Analyst", "") #Plum
  Person("nhsd.analyst", "NHSD Analyst (ex-PHE)", "") #LightGrey

  cancer.perf.lead .[#hidden] cancer.pathway.analyst
  cancer.pathway.analyst .[#hidden] cancer.data.manager

  cancer.perf.lead .[#hidden]. nhse.analyst
  cancer.pathway.analyst .[#hidden].  cancer.alliance.fd.lead 
  cancer.data.manager .[#hidden].  ca.analyst

  nhse.analyst .[#hidden]. ics.analyst
  cancer.alliance.fd.lead .[#hidden]. tre.analyst
  ca.analyst .[#hidden]. nhsd.analyst

}

@enduml