@startuml ascw-c4-container-model-CPD-with-courses
!include ascw-c4.puml
$initStep(2)
!include ascw-c4-container-model-CPD-claims-only.puml

System_Boundary(dp, "Digital Platform") {
  Container(fc, "Find CPD courses", "", $descr="Service to find CPD courses", $sprite="AzureWebApp")
  Container(cl, "Course list API", "", $descr="List of acredited CPD courses", $sprite="AzureAPIManagement")
  Rel_D(fc, cl, "Query courses", "")
}

System_Boundary(sfc, "Skills for Care") {
  ContainerDb_Ext(wts, "TP dataset", "", $descr="Accredited Training Provider dataset", $sprite="AzureSqlDatabase")
  Container_Ext(wta, "TP API", "", $descr="Training providers and courses API", $sprite="AzureAPIManagement",  $tags="tobe")
  wta -- wts
}

Rel_D(rhp, fc, "1. Find courses")
Rel_D(cl, wta, "Query courses")

SHOW_LEGEND_EX()
@enduml
