@startuml ascw-c4-container-model-base
!include ascw-c4.puml

!if (%not(%variable_exists("$with"))) 
  'default if not already set
  !global $with = VALIDATE_EMPLOYEE + VALIDATE_TP + CPD
!endif

AddRelTag("dashed", $lineStyle=DashedLine(), $legendText="external process\ndashed line")
AddElementTag("tobe", $bgColor="White", $fontColor="Gray", $borderColor="DarkGray", $legendText="to be external API")

System_Boundary(dp, "Digital Platform") {
  Container(sc, "Claim for training", "", $descr="Service to make reimbursement claims", $sprite="AzureWebApp")
  Container(vs, "Validation system", "", $descr="Validates claims based on eligibility requirements", $sprite="AzureWebApp")  
  ContainerDb(fs, "Evidence file storage", "", $descr="Stores proof of evidence provided", $sprite="AzureBlobStorage")
  Container(ps, "Payment system", "", $descr="Creates automated payment files", $sprite="AzureWebApp")
  Rel_D(sc, fs, "Store evidence")
  Rel_L(vs, fs, "Reads evidence", "")
  Rel_U(vs, ps, "Raise payments")
}

!if (with(VALIDATE_EMPLOYEE))
  System_Boundary(sfc, "Skills for Care") {
    ContainerDb_Ext(wds, "ASC Workforce Dataset", "", $descr="Employee dataset", $sprite="AzureSqlDatabase")
    Container_Ext(wda, "WDS API", "", $descr="Workforce dataset API", $sprite="AzureAPIManagement", $tags="tobe")
    wda -- wds
    Rel_D(vs, wda, "Checks employee provider relationship")
  }
!endif

!if (with(VALIDATE_TP))
  System_Boundary(sfc, "Skills for Care") {
    ContainerDb_Ext(wts, "TP dataset", "", $descr="Accredited Training Provider dataset", $sprite="AzureSqlDatabase")
    Container_Ext(wta, "TP API", "", $descr="Training providers API", $sprite="AzureAPIManagement",  $tags="tobe")
    wta -- wts
    Rel_D(vs, wta, "Check training provider accreditation", "")
  }
!endif

!if (with(VALIDATE_RHP))
  System_Boundary(nmc, "Nursing and midwifery council") {
    ContainerDb_Ext(nmr, "NMC Register", "", $descr="Registered nurse dataset", $sprite="AzureSqlDatabase")
    Container_Ext(nma, "NMC API", "", $descr="Registered nurse API", $sprite="AzureAPIManagement",  $tags="tobe")
    nma -- nmr
    Rel_D(vs, nma, "Checks registration number")
  }
!endif

!if (with(CPD))
  Person(rhp, "Regulated Health Professional", "Registered Nurses, Nurse Associates, OTs and AHPs")
!else
  Person(rhp, "Unregulated care staff" , "Healthcare assistants, care workers, support workers, live-in carers")
!endif

!if (with(VALIDATE_CQC))
  Container_Ext(cqc, "CQC API", "", $descr="CQC regulated providers", $sprite="AzureAPIManagement")
  Rel_R(vs, cqc, "Checks CQC provider")
!endif

@enduml