@startuml ascw-c4-container-model-with-courses
!include https://raw.githubusercontent.com/nhsx/dt-public/main/adult-social-care-workforce/ascw-c4-container-model-base.puml
!includesub https://raw.githubusercontent.com/nhsx/dt-public/main/adult-social-care-workforce/ascw-c4-container-model-claims-only.puml!CONTAINERS

!startsub CONTAINERS
System_Boundary(dp, "Digital Platform") {
  Container(fc, "Find training courses", "", $descr="Service to find training courses", $sprite="AzureWebApp")
  Container(cl, "Course list API", "", $descr="List of acredited training courses", $sprite="AzureAPIManagement")
  Rel_D(fc, cl, "Query courses", "")

}

!if (with(VALIDATE_TP))
  Rel_D(cl, wta, "Query courses")
!endif

Container_Ext(wta, "TP API", "", $descr="Training providers and accredited courses API", $sprite="AzureAPIManagement",  $tags="tobe")

!endsub

Rel_D(rhp, fc, "1. Find courses")
Rel_R(rhp, emp, "2. Books and attends training, informs employer")
Rel_D(emp, ilrs, "3. Records training attended")
Rel_D(ilrs, sc, "4. Uploads evidence")
Rel_L(app, ps, "5. Approves claims")
Rel_L(fin, emp, "6. Receives payments")


SHOW_LEGEND_EX()
@enduml
