@startuml ascw-c4-container-model-CPD-base
!include https://raw.githubusercontent.com/nhsx/dt-public/main/adult-social-care-workforce/ascw-c4.puml

AddRelTag("dashed", $lineStyle=DashedLine(), $legendText="external process\ndashed line")
AddElementTag("tobe", $bgColor="White", $fontColor="Gray", $borderColor="DarkGray", $legendText="to be external API")

System_Boundary(dp, "Digital Platform") {
  Container(sc, "Claim for CPD", "", $descr="Service to make indiviudual CPD claims", $sprite="AzureWebApp")
  Container(vs, "Validation system", "", $descr="Validates claims based on eligibility requirements", $sprite="AzureWebApp")  
  ContainerDb(fs, "Evidence file storage", "", $descr="Stores proof of evidence provided", $sprite="AzureBlobStorage")
  Container(ps, "Payment system", "", $descr="Creates automated payment files", $sprite="AzureWebApp")
}

System_Boundary(sfc, "Skills for Care") {
  ContainerDb_Ext(wds, "ASC Workforce Dataset", "", $descr="Employee dataset", $sprite="AzureSqlDatabase")
  Container_Ext(wda, "WDS API", "", $descr="Workforce dataset API", $sprite="AzureAPIManagement", $tags="tobe")
  wda -- wds
  'ContainerDb_Ext(wts, "TP dataset", "", $descr="Accredited Training Provider dataset", $sprite="AzureSqlDatabase")
  'ContainerDb_Ext(wta, "TP API", "", $descr="Training providers API", $sprite="AzureAPIManagement",  $tags="tobe")
  'wta -- wts
}

System_Boundary(nmc, "Nursing and midwifery council") {
  ContainerDb_Ext(nmr, "NMC Register", "", $descr="Registered nurse dataset", $sprite="AzureSqlDatabase")
  Container_Ext(nma, "NMC API", "", $descr="Registered nurse API", $sprite="AzureAPIManagement",  $tags="tobe")
  nma -- nmr
}

Container_Ext(cqc, "CQC API", "", $descr="CQC regulated providers", $sprite="AzureAPIManagement")

Rel_D(sc, fs, "Store evidence")
Rel_L(vs, fs, "Reads evidence", "")

Rel_D(vs, nma, "Checks registration number")
Rel_R(vs, cqc, "Checks CQC provider")
Rel_D(vs, wda, "Checks employee provider relationship")
'Rel_D(vs, wta, "Checks training provider details")

Rel_U(vs, ps, "Raise payments")

@enduml