@startuml ascw-c4-container-model-CPD-direct
!include https://raw.githubusercontent.com/nhsx/dt-public/main/adult-social-care-workforce/ascw-c4-container-model-CPD-base.puml

AddRelTag("dashed", $lineStyle=DashedLine(), $legendText="external process\ndashed line")
AddElementTag("tobe", $bgColor="White", $fontColor="Gray", $borderColor="DarkGray", $legendText="to be external API")
Person(rhp, "Regulated Health Professional", "Registered Nurses, Nurse Associates, OTs and AHPs")

Container_Ext(pf, "Payment File", "", $sprite="&file,scale=5.0")

Component(cert, "CPD certificate", "pdf")

Container_Ext(fin, "Finance system", "", $descr="Process payments")

Rel_L(rhp, cert, "1. Books and attends training, receives certificate", "")
Rel_D(cert, sc, "2. Makes claim, picks employer from provider list and uploads evidence", "")

ps -> pf
pf .> fin

Rel_L(fin, rhp, "3. Receives payments", $tags="dashed")

SHOW_LEGEND_EX()

@enduml
