@startuml ascw-c4-container-model-CPD-claims-only
!include ascw-c4-container-model-CPD-base.puml

AddRelTag("dashed", $lineStyle=DashedLine())

Container(sc, "Submit CPD claims", "", $descr="Service to bulk upload CPD claims", $sprite="AzureWebApp")

Person(rhp, "Regulated Health Professional", "Registered Nurses, Nurse Associates, OTs and AHPs")

Person(emp, "Employer", "CQC regulated ASC provider")

Person(app, "Approver", "Human who approves claims")

Component(ilrs, "Individual Learning Records", "CSV", $sprite="&file,scale=5.0,color=Azure")

Container_Ext(pf, "Payment File", "", $sprite="&file,scale=5.0")

Container_Ext(fin, "Finance system", "", $descr="Process payments")

Rel_R(rhp, emp, "$step(). Books and attends training, informs employer", "")
Rel_D(emp, ilrs, "$step(). Records CPD", "")
Rel_D(ilrs, sc, "$step(). Uploads evidence", "")
Rel_R(app, ps, "$step(). Approves claim")
Rel_L(fin, emp, "$step(). Receives payments", $tags="dashed")

pf <-- ps
fin <.. pf

SHOW_LEGEND_EX()

@enduml
