@startuml ascw-c4
!include <azure/AzureCommon>
!include <azure/Web/AzureWebApp>
!include <azure/Web/AzureAPIManagement>
!include <azure/Databases/AzureSqlDatabase>
!include <azure/Storage/AzureBlobStorage>
!include <C4/C4_Container>
!include <C4/C4_Component>

!unquoted procedure SHOW_LEGEND_EX()
  ' hack the legend slightly
  !$tagDefaultLegend = "person\ncontainer\ncomponent\nexternal_container\n"
  !$tagCustomLegend = "tobe\n"
  SHOW_LEGEND()
!endprocedure

!unquoted function with($b)
!$x = 0
!while ($x < %strlen($with))
    !$c = %substr($with,$x,1)
    !if ($c == $b)
        !return %true()
    !endif
    !$x = $x+1
!endwhile
!return %false()
!endfunction

!VALIDATE_EMPLOYEE = "E"
!VALIDATE_TP = "T"
!VALIDATE_CQC = "C"
!VALIDATE_RHP = "R"
!VALIDATE_ALL = VALIDATE_EMPLOYEE + VALIDATE_TP + VALIDATE_CQC + VALIDATE_RHP 

@enduml
